[package]
name = "daemon_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.46.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
rpassword = "7.4.0"
secrecy = "0.10.3"
pgp = "0.17.0"
rand = "0.9.2"
